### ISSUE TITLE
一些常用的css总结

### ISSUE THREAD

**Issue by lianxiaozhuang** [lianxiaozhuang/blog#1]
### Css Hack
+ 仅火狐识别的
``` css
@-moz-document url-prefix() {
   .selector { property: value; }
 }
```
+ 仅webkit 识别
``` css
@media screen and (-webkit-min-device-pixel-ratio:0) { 
  .selector { property: value; } 
}
```
### 媒体查询
``` css
@media screen and (max-device-width: 480px) {
  .demo { color: red; }
 }
@media screen and (min-width:960px) and (max-width:1200px){
   .demo { color: blue; }
}
```
### ie兼容半透明
+ rgba 和兼容写法
```css
/*ie8*/
background: rgba(51,54,63,0.9);
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#E533363f",endColorstr="#E533363f");
/*
0.1--19;  0.2--33; 0.3--4C ;  0.4--66;  0.5--7F;  0.6--99;  0.7--82;  0.8--C8;  0.9--E5;
*/
```
+ opacity 和兼容写法
```css
/*opacity*/
.div{
  filter:alpha(opacity=30);
  opacity:0.3
}
/*除去ie9*/
:root  .div{
  filter:none;
}
```
### ie8渐变：
```css
 background: linear-gradient(to right, #8ed9f7, #8ebcfe); 
 filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#8ed9f7', endColorstr='#8ebcfe', GradientType=1);
/*
GradientType 0/1
*/
```
### 移动端一像素（上方）
``` css
.Bbottom{position:relative;}
.Bbottom:after{
    position:absolute;
    content: "";
    height:1px;
    background:#d5d5d5;
    width:100%;
    bottom:0;
    left:0;
    -webkit-transform:scaleY(.5);
    -ms-transform:scaleY(.5);
    -o-transform:scaleY(.5);
    transform:scaleY(.5);
}
```
### 边框很细的Table
``` css
table {
	border-top:1px solid #add9c0;
	border-left:1px solid #add9c0;
}
table td{
	border-bottom:1px solid #add9c0;
	border-right:1px solid #add9c0; 
}
```
### IOS的H5页面滑动不流畅的问题
``` css
body{
	 -webkit-overflow-scrolling : touch;
}
```
